language: ruby
before_install: gem install bundler
rvm:
  - 1.9.3
  - 2.1.2
cache: bundler
script:
  - RAILS_ENV=test bundle exec rspec
addons:
  code_climate:
    repo_token: d510f30cd1b78a7511c9e3f8a035a5734c2a2a39f389b1fdceb6a0167327eca7
